### ISSUE TITLE
ContextMenu.closemenu called without an event being passed to it

### ISSUE THREAD

**Issue by stevehickman** [pascoual/meteor-bootstrap-contextmenu#1]
closemenu takes an event parameter (contextmenu.js, line 78):
closemenu: function(e) { ...}

However it is called in ContextMenu.show() without passing the event parameter (contextmenu.js, line 55):
    this.closemenu();               

This causes an exception on line 100 of contextmenu.js because e (the event) is not defined:

```
        // Don't propagate click event so other currently                                        // 90
        // opened menus won't close.                                                             // 91
        e.stopPropagation();   
```

.

**Comment by jfraboni** [comment]
+1: This happens when a context menu is open and a request to open a second context menu forces the close of the first.

**Comment by pascoual** [comment]
Thanks @stevehickman just merged PR
